// Do not edit this file!

// Creates a RestrictedArray with restricted functionality for use in an ArrayList.
function createRestrictedArray<T>({ capacity }: { capacity: number }): T[] {
  return Object.seal(
    new Proxy(Array.from({ length: capacity }), {
      get(target, prop) {
        if (prop === Symbol.toPrimitive) {
          return () => {
            const values = Object.keys(target)
              .filter((key) => /^\d+$/.test(key))
              .sort((key1, key2) => Number(key1) - Number(key2))
              .map((key) => JSON.stringify(target[Number(key)]));
            return `[${values.join(", ")}]`;
          };
        }
        if (typeof prop === "string" && /^\d+$/.test(prop)) {
          return target[Number(prop)];
        }
        if (prop in target) {
          throw new Error(
            `Avoid accessing forbidden method/property \`${String(prop)}\`!`,
          );
        }
        return undefined;
      },
      set(target, prop, value) {
        if (typeof prop === "string" && /^\d+$/.test(prop)) {
          target[Number(prop)] = value;
          return true;
        }
        throw new Error(
          `Avoid accessing forbidden method/property \`${String(prop)}\`!`,
        );
      },
    }),
  );
}

// Defines an ArrayList with functionality emulating that of a JS/TS array.
export class ArrayList<T> {
  _internalArray: T[];
  _capacity: number;
  _length: number;

  constructor(capacity: number) {
    this._internalArray = createRestrictedArray<T>({ capacity });
    this._capacity = capacity;
    this._length = 0;
    return new Proxy(this, {
      get(target, prop, receiver) {
        if (typeof prop === "string" && /^\d+$/.test(prop)) {
          return target._internalArray[Number(prop)];
        }
        return Reflect.get(target, prop, receiver);
      },
      set(target, prop, value, receiver) {
        if (typeof prop === "string" && /^\d+$/.test(prop)) {
          target._internalArray[Number(prop)] = value;
          return true;
        }
        return Reflect.set(target, prop, value, receiver);
      },
    });
  }

  [Symbol.toPrimitive](): string {
    let stringRepresentation = "[";
    for (let i = 0; i < this.length; i++) {
      if (i > 0) {
        stringRepresentation += ", ";
      }
      stringRepresentation += this._internalArray[i];
    }
    stringRepresentation += "]";
    return stringRepresentation;
  }

  get capacity(): number {
    return this._capacity;
  }

  get length(): number {
    return this._length;
  }

  doubleCapacity(): void {
    const newInternalArray = createRestrictedArray<T>({
      capacity: this.capacity * 2,
    });
    for (let i = 0; i < this.length; i++) {
      newInternalArray[i] = this._internalArray[i];
    }
    this._internalArray = newInternalArray;
    this._capacity *= 2;
  }
}
