// Do not edit this file!

export class SinglyLinkedListNode<T> {
  value: T;
  next: SinglyLinkedListNode<T> | null;

  constructor(value: T) {
    this.value = value;
    this.next = null;
  }

  [Symbol.toPrimitive](): string {
    return `Node(value=${this.value})`;
  }
}

export class SinglyLinkedList<T> {
  head: SinglyLinkedListNode<T> | null;

  constructor() {
    this.head = null;
  }

  [Symbol.toPrimitive](): string {
    let stringRepresentation = "[";
    let currentNode = this.head;
    while (currentNode) {
      if (currentNode !== this.head) {
        stringRepresentation += ", ";
      }
      stringRepresentation += currentNode.value;
      currentNode = currentNode.next;
    }
    stringRepresentation += "]";
    return stringRepresentation;
  }
}
